codecov:
  disable_default_path_fixes: no

fixes:
  - "/__w/cvise/cvise/objdir::"
  - "/__w/cvise/cvise/::"
ignore:
  - "**/include"
  - "cvise/tests"
  - "/__w/cvise/cvise/objdir/delta/topformflat.c"
  - "/__w/cvise/cvise/objdir/clex/strlex.c"
  - "/__w/cvise/cvise/objdir/clex/clex.c"
