name: Build LLVM nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  CI-LLVM-nightly:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:rolling

    steps:
      - run: apt-get update
      - run: apt-get -qq install -y gcc g++ wget lsb-release wget software-properties-common gnupg git cmake flex python3-pebble python3-psutil python3-chardet python3-pytest vim unifdef
      - run: wget https://apt.llvm.org/llvm.sh
      - run: chmod +x llvm.sh
      - run: ./llvm.sh 18
      - run: apt-get install -y bolt-18 clang-18 libclang-common-18-dev libclang-18-dev mlir-18-tools llvm-18-tools libclang-common-18-dev libclang-18-dev libclang1-18 clang-format-18 python3-clang-18 clangd-18 clang-tidy-18 libomp-18-dev
      - uses: actions/checkout@v3
      - run: mkdir objdir
      - run: cmake ..
        working-directory: objdir
      - run: make -j`nproc` VERBOSE=1
        working-directory: objdir
      - run: pytest
        working-directory: objdir
