name: Build LLVM nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LLVM_RELEASE: 18

jobs:
  CI-LLVM-nightly:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:rolling

    steps:
      - run: apt-get update
      - run: apt-get -qq install -y gcc g++ wget lsb-release wget software-properties-common gnupg git cmake flex python3-pebble python3-psutil python3-chardet python3-pytest vim unifdef
      - run: wget https://apt.llvm.org/llvm.sh
      - run: chmod +x llvm.sh
      - run: ./llvm.sh $LLVM_RELEASE
      - run: apt-get install -y bolt-$LLVM_RELEASE clang-$LLVM_RELEASE libclang-common-$LLVM_RELEASE-dev libclang-$LLVM_RELEASE-dev mlir-$LLVM_RELEASE-tools \
          libclang-common-$LLVM_RELEASE-dev libclang-$LLVM_RELEASE-dev libclang1-$LLVM_RELEASE clang-format-$LLVM_RELEASE \
          clangd-$LLVM_RELEASE clang-tidy-$LLVM_RELEASE libomp-$LLVM_RELEASE-dev
      - uses: actions/checkout@v3
      - run: mkdir objdir
      - run: cmake ..
        working-directory: objdir
      - run: make -j`nproc` VERBOSE=1
        working-directory: objdir
      - run: pytest
        working-directory: objdir
