name: Build LLVM nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LLVM_RELEASE: 18

jobs:
  CI-LLVM-nightly:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:rolling

    steps:
      - run: apt-get update
      - run: apt-get -qq install -y gcc g++ wget lsb-release wget software-properties-common gnupg git cmake flex python3-pebble python3-psutil python3-chardet python3-pytest vim unifdef
      - run: wget https://apt.llvm.org/llvm.sh
      - run: chmod +x llvm.sh
      - run: ./llvm.sh 17
      - run: apt-get install -y bolt-$LLVM_VERSION clang-$LLVM_VERSION libclang-common-$LLVM_VERSION-dev libclang-$LLVM_VERSION-dev mlir-$LLVM_VERSION-tools \
          llvm-$LLVM_VERSION-tools libclang-common-$LLVM_VERSION-dev libclang-$LLVM_VERSION-dev libclang1-$LLVM_VERSION clang-format-$LLVM_VERSION \
          python3-clang-$LLVM_VERSION clangd-$LLVM_VERSION clang-tidy-$LLVM_VERSION libomp-$LLVM_VERSION-dev
      - uses: actions/checkout@v3
      - run: mkdir objdir
      - run: cmake ..
        working-directory: objdir
      - run: make -j`nproc` VERBOSE=1
        working-directory: objdir
      - run: pytest
        working-directory: objdir
